---
- import_playbook: node-playbook.yml

- hosts: all
  become: true
  vars:
    home_directory: /home/administrator/
    cni_provider: https://docs.projectcalico.org/v3.7/manifests/calico.yaml
    master_node_ip_address: 192.168.1.100
    pod_network: 10.10.0.0/16    
  tasks:
  - name: autostart Kubelet
    systemd:
      name: kubelet
      state: started
      enabled: yes

  - name: autostart Docker
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="{{master_node_ip_address}}" --apiserver-cert-extra-sans="{{master_node_ip_address}}" --pod-network-cidr="{{pod_network}}"

  - name: Setup kubeconfig for vagrant user
    command: "{{ item }}"
    with_items:
     - mkdir -p "{{home_directory}}".kube
     - cp /etc/kubernetes/admin.conf "{{home_directory}}".kube/config
     - chown administrator:administrator "{{home_directory}}".kube/config

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

  - name: Install CNI provider
    become: false
    command: kubectl apply -f "{{cni_provider}}"

  - name: Install Kubernetes Dashboard
    become: false
    command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml
